openapi: 3.0.1
info:
  version: "0.0.1"
  title: "Family Branch"
  description: "desc."

  contact:
    name: "Ehsan Munna"
    email: "grmunnabd@gmail.com"

servers:
  - url: 'http://localhost:3000/api/v1'
  - url: 'https://localhost:3000/api/v1'

tags:
- name: "Person"
  description: "api for managing person"
- name: "Family Person"
  description: "api for managing family person"

paths:
  /persons:
    post:
      tags:
      - "Person"
      summary: "Add a new person"
      requestBody:
        description: Person object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        "405":
          description: "Invalid input"
    get:
      tags:
        - "Person"
      summary: find all person
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '400':
          description: Invalid status value
          content: {}
  /familyperson:
    post:
      tags:
        - "Family Person"
      summary: "Add a new family person"
      requestBody:
        description: Family Person object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FamilyPerson'
      responses:
        "405":
          description: "Invalid input"
    get:
      tags:
        - "Family Person"
      summary: find all family person
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FamilyPerson'
        '400':
          description: Invalid status value
          content: {}
  /familyperson/details:
    get:
      tags:
        - "Family Person"
      summary: find all family person in details
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FamilyPerson'
        '400':
          description: Invalid status value
          content: {}

components:
  schemas:
    Person:
      type: object
      properties:
        name:
          type: "string"
        phone:
          type: "string"

    FamilyPerson:
        type: object
        properties:
          person:
            type: "string"
          spouse:
            type: "string"
          children:
            type: "string"