info:
  version: "0.0.1"
  title: "Family Branch"
  description: "desc."

  contact:
    name: "Ehsan Munna"
    email: "grmunnabd@gmail.com"

host: "localhost:3000"
basePath: "/api/v1/"
schemes:
  - http
  - https

consumes:
  - application/json
produce:
  - application/json

tags:
- name: "Person"
  description: "api for managing person"
- name: "Family Person"
  description: "api for managing family person"

paths:
  person:
    post:
      tags:
      - "Person"
      summary: "Add a new person"
      consumes:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Person object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Person"
      responses:
        "405":
          description: "Invalid input"

definitions:
  Person:
    type: "Object"
    properties:
      name:
        type: "string"
      phone:
        type: "string"